version: "3.9"
services:
  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    ports:
      - "27017:27017"
      - "5000:8080"
    # network_mode: bridge
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    # network_mode: bridge
  react:
    build: ./react-app
    container_name: react
    restart: always
    stdin_open: true
    depends_on:
      - flask
    ports:
      - "8081:3000"
    # expose:
    #   - 8081
